#-------------------------------
# General Site Settings
baseURL = "https://fabiangonzalez.dev"
languageCode = "en-us"
title = "Avenco"
googleAnalytics = "G-4DGKG29WJM" # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Pagination settings:

# For Hugo versions 0.128.0 and above, use the following settings:
# This will set the number of items per page for newer versions.
[pagination]
  pagerSize = 6

# For Hugo versions below 0.128.0, uncomment the line below and comment out the [pagination] block above:
#paginate = 6 # Sets the number of items per page for older versions.


[params]
  logo = "/images/logo.png" # You can add own logo. For example "/images/logo.png".
  description = "Software Engineer expert in AEM, HTML, CSS, JS, PHP, MySQL, ReactJS. "
  enableSearch = true


[params.global.image]
  enable = true
  cover__image = '/images/background.svg' # Add global cover image (This field adds a background to the top and bottom of the site.)

#-------------------------------
# Main Menu
[menu]
 # [[menu.main]]
  #  identifier = "home"
  # name = "Home"
  # url = "/"
  # weight = 1


  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

#  [[menu.main]]
#    identifier = "posts"
#    name = "Posts"
#    url = "/posts/"
#    weight = 3
#    hasChildren = true

  [[menu.main]]
    #  parent = "Pages"
      name = "About"
      url = "/about/"
      weight = 5

  #    [[menu.main]]
   #   parent = "Pages"
    #  name = "Elements"
     # url = "/elements/"
      # weight = 2

  # Call to action button
  [params.menu.button]
  cta__button__text = "Send me a Whatsapp"
  cta__button__url = "https://api.whatsapp.com/send?phone=5491128973151"




 [params.menu.buttondos]
    cta__button__textdos = "Courses"

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Fabian Gonzalez"
    author__title = "游녦 Hello I'm Fabian Gonzalez"
    author__bio = "Software Engineer expert in AEM, HTML, CSS, JS, PHP, MySQL, ReactJS. Passionate about technology and web development 游뱁."
    author__image = "/images/600x600.png"
    author__avatar = "/images/200x200.png"
    button__text = "Send me a Whatsapp"
    button__textTwo = "See my projects"



#-------------------------------
# Services Section
[params.services]
  enable = true
  services__title = "My <span class='text-span'>Services</span>"
  services__description = "I create personalized digital solutions that drive business growth. From web development and ecommerce to mobile applications and SEO optimization, my expertise in technologies such as AEM, ReactJS, Java, and AI integration ensures high-impact results."

  [[params.services.services_list]]
    name = "Web Development"
    description = "Modern, fast, and SEO-optimized websites focused on user experience."
    icon = "bi-code-slash"

  [[params.services.services_list]]
    name = "Ecommerce Development"
    description = "Scalable and secure e-commerce platforms designed to maximize sales and conversion."
    icon = "bi-cart"

  [[params.services.services_list]]
    name = "AEM Development"
    description = "Migration, optimization, and development of solutions in Adobe Experience Manager (AEM) for efficient content management."
    icon = "bi-layers"

  [[params.services.services_list]]
    name = "Mobile App Development"
    description = "Intuitive and functional mobile applications designed to enhance user experience."
    icon = "bi-phone"

  [[params.services.services_list]]
    name = "SEO Optimization"
    description = "Website optimization for search engines, increasing visibility and organic traffic."
    icon = "bi-graph-up"

  [[params.services.services_list]]
    name = "AI Integration"
    description = "Implementation of artificial intelligence solutions to automate processes and improve decision-making."
    icon = "bi-cpu"

  #-------------------------------
  # Projects Settings
  [params.projects]
    enable = true
    projects__title= "Latest <span class='text-span'>Works</span>" # Add a 'text-span' class to highlight text.
    projects__description= "My latest web development and design work built completely with passion, simplicity & creativity!"


  [languages.es.params.projects]
    enable = true
    projects__title= "칔ltimos <span class='text-span'>Trabajos</span>" # Agrega una clase 'text-span' para resaltar el texto.
    projects__description= "Mis 칰ltimos trabajos de desarrollo web y dise침o, construidos completamente con pasi칩n, simplicidad y creatividad!"


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonial__title = "Work <span class='text-span'>Testimonials</span>" # Add a 'text-span' class to highlight text.
    testimonial__description = "Testimonials from companies and people I worked for, web development and consultancies"

  [[params.testimonial_item]]
    name = " Jorge Rannin"
    image = "/images/250x250_testimonials_georgie.png"
    designation = "Consultant Marketing Specialist"
    content = "Fabian was a pleasure to work with, he managed and created AEM Cloud consultancies for the Colgate and Palmolive team."

  [[params.testimonial_item]]
    name = "Luis Luchessi"
    image = "/images/250x250_testimonials_luis.png"
    designation = "Creator of digital properties"
    content = "Working with Fabian was an incredible experience for our digital platform, he is an exceptional professional who created a modern ecommerce system for us."

  [[params.testimonial_item]]
    name = "Roger Bergson"
    image = "/images/250x250_testimonials_roger.png"
    designation = "CEO, Founder"
    content = "Fabian met all deadlines and delivered a flawless multilingual website. His attention to detail and professionalism are second to none."


  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog__title = "Recent <span class='text-span'>Blog</span> Posts" # Add a 'text-span' class to highlight text.
    blog__description = ""


  #-------------------------------
  # Contact Settings
  [params.contact]
    enable = true
    contact__email = "fabiangonzalezdev@gmail.com" # Add your form_id
    contact__title = "<span class='text-span'>Send</span> me a whatsapp" # Add a title to your form
    contact__description = "Feel free to write me whatever you want and I will answer you quickly on whatsapp." # Add a description to your form

    # NOTE
    # Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = true
    mailchimp__title = "Contact me via <span class='text-span'>Whatsapp</span> " # Add your title
    mailchimp__text = "To talk about your project, Works, Courses, IT Consulting" # Add descriptions to the form. If you want to use more than one sentence, be sure to separate them with a comma.
    mailchimp__identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp" # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
    mailchimp__button__text = "Send me a Whatsapp" # Add your button text

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = false
    disqusShortname = "anvodstudio-demo" # Add your shortname for Disqus Comment. For example anvodstudio-demo


  #-------------------------------
  # Footer Settings
  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "X"
    link = "https://x.com/fabgonzalezdev"

    [[params.social]]
       icon = "ion-logo-github"
       name = "Github"
       link = "https://github.com/fabiangonzalezdev"

    # [[params.social]]
     #  icon = "ion-logo-pinterest"
     #  name = "Pinterest"
    #   link = "https://pinterest.com"

  [[params.social]]
    icon = "ion-logo-codepen"
    name = "Codepen"
    link = "https://codepen.io/fabiangonzalezdev"

   # [[params.social]]
    #  icon = "ion-logo-vimeo"
   #   name = "Vimeo"
    #  link = "https://vimeo.com"

  [[params.social]]
    icon = "ion-logo-youtube"
    name = "Youtube"
    link = "https://www.youtube.com/@fabiangonzalezdev"

  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "ion-logo-facebook"
  #   name = "Facebook"
  #   link = "https://facebook.com"

  # Other icons can be found at https://ionicons.com/v4/


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    contentDir = "content/en"
    weight = 1
    [languages.en.params]
      description = "Software Engineer expert in AEM, HTML, CSS, JS, PHP, MySQL, ReactJS."
    [[languages.en.menu.main]]
      identifier = "projects"
      name = "Projects"
      url = "/projects/"
      weight = 2
    [[languages.en.menu.main]]
      name = "About"
      url = "/about/"
      weight = 5
    [[languages.en.menu.main]]
      name = "Services"
      url = "/services/"
      weight = 6


        [languages.en.params.menu.button]
    cta__button__text = "Send me a Whatsapp"
    cta__button__url = "https://api.whatsapp.com/send?phone=5491128973151"

  [languages.es]
    languageName = "Espa침ol"
    languageCode = "es"
    contentDir = "content/es"
    weight = 2
    [languages.es.params]
      description = "Ingeniero de software experto en AEM, HTML, CSS, JS, PHP, MySQL, ReactJS."
    [[languages.es.menu.main]]
      identifier = "projects"
      name = "Proyectos"
      url = "/es/projects/"
      weight = 2
    [[languages.es.menu.main]]
      name = "Sobre m칤"
      url = "/es/about/"
      weight = 5
    [[languages.es.menu.main]]
      name = "Servicios"
      url = "/es/services/"
      weight = 6

  
  [languages.es.params.menu.button]
    cta__button__text = "Env칤ame un Whatsapp"
    cta__button__url = "https://api.whatsapp.com/send?phone=5491128973151"


  [languages.es.params.author]
    author__name = "Fabian Gonzalez"
    author__title = "游녦 Hola, soy Fabian Gonzalez"
    author__bio = "Ingeniero de software experto en AEM, HTML, CSS, JS, PHP, MySQL, ReactJS. Apasionado por la tecnolog칤a y el desarrollo web 游뱁."
    author__image = "/images/600x600.png"
    author__avatar = "/images/200x200.png"
    button__text = "Env칤ame un Whatsapp"
    button__textTwo = "Ver mis proyectos"

  [languages.es.params.services]
    enable = true
    services__title = "Mis <span class='text-span'>Servicios</span>"
    services__description = "Creo soluciones digitales personalizadas que impulsan el crecimiento empresarial. Desde desarrollo web y comercio electr칩nico hasta aplicaciones m칩viles y optimizaci칩n SEO, mi experiencia en tecnolog칤as como AEM, ReactJS, Java e integraci칩n de IA garantiza resultados de alto impacto."

    [[languages.es.params.services.services_list]]
      name = "Desarrollo Web"
      description = "Sitios web modernos, r치pidos y optimizados para SEO enfocados en la experiencia del usuario."
      icon = "bi-code-slash"

    [[languages.es.params.services.services_list]]
      name = "Desarrollo de Ecommerce"
      description = "Plataformas de comercio electr칩nico escalables y seguras dise침adas para maximizar ventas y conversi칩n."
      icon = "bi-cart"

    [[languages.es.params.services.services_list]]
      name = "Desarrollo AEM"
      description = "Migraci칩n, optimizaci칩n y desarrollo de soluciones en Adobe Experience Manager (AEM) para una gesti칩n eficiente de contenido."
      icon = "bi-layers"

    [[languages.es.params.services.services_list]]
      name = "Desarrollo de Apps M칩viles"
      description = "Aplicaciones m칩viles intuitivas y funcionales dise침adas para mejorar la experiencia del usuario."
      icon = "bi-phone"

    [[languages.es.params.services.services_list]]
      name = "Optimizaci칩n SEO"
      description = "Optimizaci칩n de sitios web para motores de b칰squeda, aumentando la visibilidad y el tr치fico org치nico."
      icon = "bi-graph-up"

    [[languages.es.params.services.services_list]]
      name = "Integraci칩n de IA"
      description = "Implementaci칩n de soluciones de inteligencia artificial para automatizar procesos y mejorar la toma de decisiones."
      icon = "bi-cpu"

  [languages.es.params.testimonials]
    enable = true
    testimonial__title = "Referencias de <span class='text-span'>Trabajo</span>"
    testimonial__description = "Testimonios de empresas y personas para las que he trabajado, desarrollo web y consultor칤as"

  [languages.es.params.contact]
    enable = true
    contact__email = "fabiangonzalezdev@gmail.com"
    contact__title = "<span class='text-span'>Env칤ame</span> un whatsapp"
    contact__description = "Si칠ntete libre de escribirme lo que quieras y te responder칠 r치pidamente por whatsapp."

  [languages.es.params.mailchimp]
    enable = true
    mailchimp__title = "Cont치ctame v칤a <span class='text-span'>Whatsapp</span>"
    mailchimp__text = "Para hablar sobre tu proyecto, trabajos, cursos, consultor칤a IT"
    mailchimp__identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp"
    mailchimp__button__text = "Env칤ame un Whatsapp"

# Blog en Espa침ol
[languages.es.params.blog]
  enable = true
  blog__title = "Publicaciones recientes del <span class='text-span'>Blog</span>"
  blog__description = "Mis 칰ltimas publicaciones sobre tecnolog칤a y desarrollo web."

# Proyectos en Ingl칠s
[languages.en.params.projects]
  enable = true
  projects__title = "Latest <span class='text-span'>Works</span>"
  projects__description = "My latest web development and design work built completely with passion, simplicity & creativity!"

# Testimonials en Espa침ol
[[languages.es.params.testimonial_item]]
  name = "Jorge Rannin"
  image = "/images/250x250_testimonials_georgie.png"
  designation = "Consultor especialista en marketing"
  content = "Fue un placer trabajar con Fabian, manej칩 y cre칩 consultor칤as AEM Cloud para el equipo de Colgate y Palmolive."

[[languages.es.params.testimonial_item]]
  name = "Luis Luchessi"
  image = "/images/250x250_testimonials_luis.png"
  designation = "Creador de propiedades digitales"
  content = "Trabajar con Fabian fue una experiencia incre칤ble para nuestra plataforma digital, es un profesional excepcional que cre칩 para nosotros un moderno sistema de ecommerce."

[[languages.es.params.testimonial_item]]
  name = "Roger Bergson"
  image = "/images/250x250_testimonials_roger.png"
  designation = "CEO, Fundador"
  content = "Fabian cumpli칩 todos los plazos y entreg칩 un sitio multiling칲e impecable. Su atenci칩n al detalle y profesionalismo son incomparables."